### ISSUE TITLE
New layout with cards

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#17]
In some pages with cards, there is an old layout. Create new layout pages with cards. Feel free to design, but I was thinking in somethind like this (without user image):

![cardexample](https://user-images.githubusercontent.com/17773211/66753875-10aa0500-ee6b-11e9-8964-a456e1e37bcf.jpg)

Pages: localhost:3000/missions, localhost:3000/visions, localhost:3000/csfs

![Captura de tela de 2019-10-10 11-22-19](https://user-images.githubusercontent.com/17773211/66578030-c239f500-eb50-11e9-9733-2d8f6e0b7f28.png)

**Comment by WillCranel** [comment]
I'm going to work in it, ok?
