### ISSUE TITLE
Implement responsive table

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#18]
In the page /plans/swotedit would be good a responsive table. Keep the color design and align it with the card above (in blue).

![Captura de tela de 2019-10-10 11-28-36](https://user-images.githubusercontent.com/17773211/66578354-54da9400-eb51-11e9-8b99-131e1159e573.png)

**Comment by WillCranel** [comment]
i'm going to work in it, ok?

**Comment by eduqg** [comment]
Ok @WillCranel , finish one issue and after I can give you another :+1:
