### ISSUE TITLE
Improve input fields and buttons in table

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#19]
Improve input fields of Força, Oportunidades, Fraquezas and Oportunidades to use entire width of a cell.

Now

![fields](https://user-images.githubusercontent.com/17773211/66754270-fd4b6980-ee6b-11e9-875a-89208beec4db.png)

After

![Captura de tela de 2019-10-14 10-20-54](https://user-images.githubusercontent.com/17773211/66754480-6c28c280-ee6c-11e9-9b2c-f68f9c893398.png)
* Without distortions, please.

**Comment by harshanarisetty** [comment]
Can I work on this?

**Comment by luchiago** [comment]
Hi. I would like to work on that.

**Comment by eduqg** [comment]
Go ahead @luchiago! :+1:
