### ISSUE TITLE
Improve table generated in pdf

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#20]
Improve the table generated on exported pdf's. Create divisions on the table generated to be clear to the user his Strengths, Weaknesses, Threats and Opportunities. Also, the generated table must use all the space inside the card.

To generate pdf, sign in, go to "Meu Planejamento", and click in "Gerar PDF".

![Captura de tela de 2019-10-10 11-34-37](https://user-images.githubusercontent.com/17773211/66754705-f7a25380-ee6c-11e9-8992-03fdd9a5021f.png)

**Comment by PacoLuna1** [comment]
@eduqg can I try it?

**Comment by eduqg** [comment]
Sure @PacoLuna1 :+1:

**Comment by PacoLuna1** [comment]
#21
