### ISSUE TITLE
Roles not appearing at PDF creation

### ISSUE THREAD

**Issue by filipetoyoshima** [eduqg/LifeToRemind#29]
## Description

The generated PDF document shows the "Meus Papéis" header, but it is just a blank space, I believe that what I've written on the roles section should appear there.

## Screenshots

![image](https://user-images.githubusercontent.com/29482983/68639865-ad040d80-04e4-11ea-9bc9-65a885c727bd.png)

-----------
**OBS** I've made sure that I have added roles

## System Settings

Bug on the Production Version, on Heroku: http://lifetoremindhub.herokuapp.com/myplan
Using on Chrome 78.0.3904.70 (Official Build) (64-bit)

**Comment by eduqg** [comment]
Thanks for the advice, I'll check it out.

**Comment by eduqg** [comment]
Fixed on [this commit](https://github.com/eduqg/LifeToRemind/commit/b2f0fdbe7581973f94ca23b4bba228154102e6c8). Can you check it out on [devel](http://lifetoremindhubdevel.herokuapp.com/)?. Soon it will be avaible on http://lifetoremindhub.herokuapp.com

**Comment by filipetoyoshima** [comment]
Working properly!
![image](https://user-images.githubusercontent.com/29482983/68705469-e97b4c00-056c-11ea-8a07-82e3cd48e641.png)

--------------

I didn't test all the answers together at PDF generation, which I recommend to do before production deployment.

Also, here a user suggestion: set a space between paragraphs, there is, between each role description. I think it will make the document more readable, and I believe that is not a so expensive addition to the code.

I'll close this issue due to the homolog solution. Thanks for the attention :smile:
