### ISSUE TITLE
Refactor Plans Controller

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#3]
Extract methods from plans controller. For exemple, there is many method related to pdf plan generation. Will be accepted multiple pull requests.

**Comment by nathandonato** [comment]
Hi, I'd like to take a look into this (part of it, at least). I'd like to extract the plan creation methods into a helper class, named something like `PlansHashImporter`, which would be called on [line 317](https://github.com/eduqg/LifeToRemind/blob/master/app/controllers/plans_controller.rb#L317) of the controller.

If that's a suitable solution, where in the project would you like the importer? I was thinking maybe in a directory `app/importers`.

**Comment by eduqg** [comment]
Hello @nathandonato, at some point I have searched to use rake tasks to import and export methods of a plan.

But inside the app/helpers there are files to be used as helpers. Refactor some methods to plans_helper.rb, it might be the solution for what we want.

**Comment by nathandonato** [comment]
Hi @eduqg, I opened up a PR for the `import` changes. I put the new code in an `app/importers` directory because I felt importers are more specific than helpers, but I'd be happy to move them wherever you'd like. Just let me know in the PR review.
