### ISSUE TITLE
Devise Mailer

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#5]
All user structure are defined. Configure devise mailer to recover password.

**Comment by andela-mogala** [comment]
Hi, do you mind if I pick this up?

**Comment by eduqg** [comment]
Go on @andela-mogala ! :+1:

**Comment by andela-mogala** [comment]
Thanks @eduqg. Just for clarity, what should be the expected behaviour when this task is completed. 
If you can put in the format below

- When user does x, the system does y
...

**Comment by eduqg** [comment]
Hey @andela-mogala. I should have clarified before.

In the page for login, must have a link with 'Forgot password?'. When the user click on it, one email must be sent with a link to recover the password. After that, the user must be redirected to one page to update a new password.

Must be created one config.action_mailer in initializers/development.rb. This [link](https://medium.com/@nikhilbhavsar07/account-activation-and-password-reset-using-devise-4deabe9cd9c0) might help.
