### ISSUE TITLE
Flash messages overlay

### ISSUE THREAD

**Issue by eduqg** [eduqg/LifeToRemind#8]
Flash messages should overlay instead of creating white space when appear.

![Captura de tela de 2019-10-08 18-26-12](https://user-images.githubusercontent.com/17773211/66434535-23e74b80-e9f9-11e9-90bc-968c7d8acb69.png)

**Comment by Sean-HL-Lin** [comment]
working on it

**Comment by decabeza** [comment]
Hi @eduqg! I would like work on this issue, is possible? 😃

**Comment by eduqg** [comment]
Yes it is @decabeza! :+1:
